Covalent Bond: /home/wang/covalentBond/src/core/server/task/cbTable.cpp File Reference
cbTable.cpp File Reference
The impl of table.
#include "cbTable.hpp"
#include <workflow/MySQLResult.h>
Functions
void mapShared2Virtual (cbVirtualSharedTable *sharedT, cbVirtualTable *virtualT)
std::vector< cbMySQLCell * > __luaPackedCellAsVec (cbMySQLCell *v)
std::vector< std::string > __luaPackedStringAsVec ()
Detailed Description
The impl of table.
Author
chenghua Wang (cheng.nosp@m.hua..nosp@m.wang..nosp@m.edu@.nosp@m.gmail.nosp@m..com)
Version
0.1
Date
2022-11-10
Copyright
Copyright (c) 2022
Definition in file cbTable.cpp.
Function Documentation
__luaPackedCellAsVec()
std::vector<cbMySQLCell*> __luaPackedCellAsVec (cbMySQLCell * v)
Definition at line 465 of file cbTable.cpp.
Referenced by cb::graph::cbComputeGraph::cbComputeGraph().
__luaPackedStringAsVec()
std::vector<std::string> __luaPackedStringAsVec ()
Definition at line 472 of file cbTable.cpp.
Referenced by cb::graph::cbComputeGraph::cbComputeGraph().
mapShared2Virtual()
void mapShared2Virtual (cbVirtualSharedTable * sharedT, cbVirtualTable * virtualT)
Definition at line 230 of file cbTable.cpp.
References cbVirtualSharedTable::atPtr(), cbVirtualTable::atPtrRef(), cbVirtualSharedTable::getInfo(), cbVirtualSharedTable::getShape(), cbVirtualTable::getShape(), makeShapeFull(), cbVirtualTable::resetShape(), and cbVirtualTable::setInfo().
Referenced by cb::graph::cbVirtualDeviceNode::generateTask().