Covalent Bond: cbMySQLCell Class Reference
cbMySQLCell Class Reference
#include <cbTable.hpp>
Public Member Functions
cbMySQLCell ()
cbMySQLCell (const protocol::MySQLCell &m)
cbMySQLCell (int value)
cbMySQLCell (float value)
cbMySQLCell (double value)
cbMySQLCell (unsigned long long value)
cbMySQLCell (const std::string &value)
cbMySQLCell (const std::string &value, const cbMySQLType &t)
bool isNull () const
bool isInt () const
bool isString () const
bool isFloat () const
bool isDouble () const
bool isULL () const
bool isDate () const
bool isTime () const
bool isDatetime () const
int asInt () const
std::string asString () const
float asFloat () const
double asDouble () const
unsigned long long asULL () const
std::string asDate () const
std::string asTime () const
std::string asDatetime () const
void setInt (int value)
void setString (const std::string &value)
void setFloat (float value)
void setDouble (double value)
void setULL (unsigned long long value)
void setDate (const std::string &value)
void setTime (const std::string &value)
void setDatetime (const std::string &value)
cbMySQLType getType ()
Private Attributes
cbMySQLType m_type = cbMySQLType::Null
__cbMySQLMeta m_data
Detailed Description
Definition at line 468 of file cbTable.hpp.
Constructor & Destructor Documentation
cbMySQLCell() [1/8]
cbMySQLCell::cbMySQLCell () inline
Definition at line 470 of file cbTable.hpp.
cbMySQLCell() [2/8]
cbMySQLCell::cbMySQLCell (const protocol::MySQLCell & m)
Definition at line 304 of file cbTable.cpp.
References DataTime, Date, Double, Float, Int, m_data, m_type, Null, String, Time, and ULL.
cbMySQLCell() [3/8]
cbMySQLCell::cbMySQLCell (int value) inline
Definition at line 472 of file cbTable.hpp.
cbMySQLCell() [4/8]
cbMySQLCell::cbMySQLCell (float value) inline
Definition at line 473 of file cbTable.hpp.
cbMySQLCell() [5/8]
cbMySQLCell::cbMySQLCell (double value) inline
Definition at line 474 of file cbTable.hpp.
cbMySQLCell() [6/8]
cbMySQLCell::cbMySQLCell (unsigned long long value) inline
Definition at line 475 of file cbTable.hpp.
cbMySQLCell() [7/8]
cbMySQLCell::cbMySQLCell (const std::string & value) inline
Definition at line 476 of file cbTable.hpp.
cbMySQLCell() [8/8]
cbMySQLCell::cbMySQLCell (const std::string & value, const cbMySQLType & t) inline
Definition at line 477 of file cbTable.hpp.
Member Function Documentation
asDate()
std::string cbMySQLCell::asDate () const
Definition at line 425 of file cbTable.cpp.
References asString().
asDatetime()
std::string cbMySQLCell::asDatetime () const
Definition at line 429 of file cbTable.cpp.
References asString().
Referenced by bindAllFuncByDefault().
asDouble()
double cbMySQLCell::asDouble () const
Definition at line 415 of file cbTable.cpp.
References isDouble(), and m_data.
Referenced by bindAllFuncByDefault().
asFloat()
float cbMySQLCell::asFloat () const
Definition at line 410 of file cbTable.cpp.
References isFloat(), and m_data.
Referenced by bindAllFuncByDefault().
asInt()
int cbMySQLCell::asInt () const
Definition at line 400 of file cbTable.cpp.
References isInt(), and m_data.
Referenced by bindAllFuncByDefault().
asString()
std::string cbMySQLCell::asString () const
Definition at line 405 of file cbTable.cpp.
References isString(), and m_data.
Referenced by asDate(), asDatetime(), asTime(), and bindAllFuncByDefault().
asTime()
std::string cbMySQLCell::asTime () const
Definition at line 427 of file cbTable.cpp.
References asString().
Referenced by bindAllFuncByDefault().
asULL()
unsigned long long cbMySQLCell::asULL () const
Definition at line 420 of file cbTable.cpp.
References isULL(), and m_data.
Referenced by bindAllFuncByDefault().
getType()
cbMySQLType cbMySQLCell::getType ()
Definition at line 463 of file cbTable.cpp.
References m_type.
isDate()
bool cbMySQLCell::isDate () const
Definition at line 379 of file cbTable.cpp.
References Date, and m_type.
Referenced by setDate().
isDatetime()
bool cbMySQLCell::isDatetime () const
Definition at line 393 of file cbTable.cpp.
References DataTime, and m_type.
Referenced by bindAllFuncByDefault(), and setDatetime().
isDouble()
bool cbMySQLCell::isDouble () const
Definition at line 365 of file cbTable.cpp.
References Double, and m_type.
Referenced by asDouble(), bindAllFuncByDefault(), and setDouble().
isFloat()
bool cbMySQLCell::isFloat () const
Definition at line 358 of file cbTable.cpp.
References Float, and m_type.
Referenced by asFloat(), bindAllFuncByDefault(), and setFloat().
isInt()
bool cbMySQLCell::isInt () const
Definition at line 341 of file cbTable.cpp.
References Int, and m_type.
Referenced by asInt(), bindAllFuncByDefault(), and setInt().
isNull()
bool cbMySQLCell::isNull () const
Definition at line 334 of file cbTable.cpp.
References m_type, and Null.
isString()
bool cbMySQLCell::isString () const
Definition at line 348 of file cbTable.cpp.
References DataTime, Date, m_type, String, and Time.
Referenced by asString(), bindAllFuncByDefault(), and setString().
isTime()
bool cbMySQLCell::isTime () const
Definition at line 386 of file cbTable.cpp.
References m_type, and Time.
Referenced by bindAllFuncByDefault(), and setTime().
isULL()
bool cbMySQLCell::isULL () const
Definition at line 372 of file cbTable.cpp.
References m_type, and ULL.
Referenced by asULL(), bindAllFuncByDefault(), and setULL().
setDate()
void cbMySQLCell::setDate (const std::string & value)
Definition at line 451 of file cbTable.cpp.
References isDate(), and m_data.
setDatetime()
void cbMySQLCell::setDatetime (const std::string & value)
Definition at line 459 of file cbTable.cpp.
References isDatetime(), and m_data.
Referenced by bindAllFuncByDefault().
setDouble()
void cbMySQLCell::setDouble (double value)
Definition at line 443 of file cbTable.cpp.
References isDouble(), and m_data.
setFloat()
void cbMySQLCell::setFloat (float value)
Definition at line 439 of file cbTable.cpp.
References isFloat(), and m_data.
Referenced by bindAllFuncByDefault().
setInt()
void cbMySQLCell::setInt (int value)
Definition at line 431 of file cbTable.cpp.
References isInt(), and m_data.
Referenced by bindAllFuncByDefault().
setString()
void cbMySQLCell::setString (const std::string & value)
Definition at line 435 of file cbTable.cpp.
References isString(), and m_data.
Referenced by bindAllFuncByDefault().
setTime()
void cbMySQLCell::setTime (const std::string & value)
Definition at line 455 of file cbTable.cpp.
References isTime(), and m_data.
Referenced by bindAllFuncByDefault().
setULL()
void cbMySQLCell::setULL (unsigned long long value)
Definition at line 447 of file cbTable.cpp.
References isULL(), and m_data.
Referenced by bindAllFuncByDefault().
Member Data Documentation
m_data
__cbMySQLMeta cbMySQLCell::m_data private
Definition at line 511 of file cbTable.hpp.
Referenced by asDouble(), asFloat(), asInt(), asString(), asULL(), cbMySQLCell(), setDate(), setDatetime(), setDouble(), setFloat(), setInt(), setString(), setTime(), and setULL().
m_type
cbMySQLType cbMySQLCell::m_type = cbMySQLType::Null private
Definition at line 510 of file cbTable.hpp.
Referenced by cbMySQLCell(), getType(), isDate(), isDatetime(), isDouble(), isFloat(), isInt(), isNull(), isString(), isTime(), and isULL().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbTable.hpp
/home/wang/covalentBond/src/core/server/task/cbTable.cpp