Covalent Bond: cbMySQLField Class Reference
cbMySQLField Class Reference
A copy move from workflow MySQLResult.h and .inl file.
#include <cbTable.hpp>
Public Member Functions
cbMySQLField ()
Construct a new cb My S Q L Field object.
cbMySQLField (const protocol::MySQLField *wfPtr)
Construct a new cb My S Q L Field object.
cbMySQLField (const cbMySQLField *ptr)
std::string getName () const
std::string getOrgName () const
std::string getTable () const
std::string getOrgTable () const
std::string getDB () const
std::string getCatalog () const
std::string getDef () const
int getCharsetnr () const
int getLength () const
int getFlags () const
int getDecimals () const
int getDataType () const
void setName (const std::string &value)
void setOrgName (const std::string &value)
void setTable (const std::string &value)
void setOrgTable (const std::string &value)
void setDB (const std::string &value)
void setCatalog (const std::string &value)
void setDef (const std::string &value)
void setCharsetnr (int32_t value)
void setLength (int32_t value)
void setFlags (int32_t value)
void setDecimals (int32_t value)
void setDataType (int32_t value)
Private Attributes
std::string m_name
std::string m_orgName
std::string m_table
std::string m_orgTable
std::string m_db
std::string m_catalog
std::string m_def
int m_length
int m_flags
int m_decimals
int m_charsetnr
int m_data_type
Detailed Description
A copy move from workflow MySQLResult.h and .inl file.
Copyright (c) 2019 Sogou, Inc.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 404 of file cbTable.hpp.
Constructor & Destructor Documentation
cbMySQLField() [1/3]
cbMySQLField::cbMySQLField ()
Construct a new cb My S Q L Field object.
Definition at line 243 of file cbTable.cpp.
cbMySQLField() [2/3]
cbMySQLField::cbMySQLField (const protocol::MySQLField * wfPtr)
Construct a new cb My S Q L Field object.
Parameters
wfPtr
Definition at line 245 of file cbTable.cpp.
References m_catalog, m_charsetnr, m_data_type, m_db, m_decimals, m_def, m_flags, m_length, m_name, m_orgName, m_orgTable, and m_table.
cbMySQLField() [3/3]
cbMySQLField::cbMySQLField (const cbMySQLField * ptr)
Definition at line 260 of file cbTable.cpp.
References getCatalog(), getCharsetnr(), getDataType(), getDB(), getDecimals(), getDef(), getFlags(), getLength(), getName(), getOrgName(), getOrgTable(), getTable(), m_catalog, m_charsetnr, m_data_type, m_db, m_decimals, m_def, m_flags, m_length, m_name, m_orgName, m_orgTable, and m_table.
Member Function Documentation
getCatalog()
std::string cbMySQLField::getCatalog () const
Definition at line 282 of file cbTable.cpp.
References m_catalog.
Referenced by cbMySQLField().
getCharsetnr()
int cbMySQLField::getCharsetnr () const
Definition at line 284 of file cbTable.cpp.
References m_charsetnr.
Referenced by cbMySQLField().
getDataType()
int cbMySQLField::getDataType () const
Definition at line 288 of file cbTable.cpp.
References m_data_type.
Referenced by cbMySQLField().
getDB()
std::string cbMySQLField::getDB () const
Definition at line 281 of file cbTable.cpp.
References m_db.
Referenced by cbMySQLField().
getDecimals()
int cbMySQLField::getDecimals () const
Definition at line 287 of file cbTable.cpp.
References m_decimals.
Referenced by cbMySQLField().
getDef()
std::string cbMySQLField::getDef () const
Definition at line 283 of file cbTable.cpp.
References m_def.
Referenced by cbMySQLField().
getFlags()
int cbMySQLField::getFlags () const
Definition at line 286 of file cbTable.cpp.
References m_flags.
Referenced by cbMySQLField().
getLength()
int cbMySQLField::getLength () const
Definition at line 285 of file cbTable.cpp.
References m_length.
Referenced by cbMySQLField().
getName()
std::string cbMySQLField::getName () const
Definition at line 276 of file cbTable.cpp.
References m_name.
Referenced by cbMySQLField(), and cbVirtualTable::colNameAt().
getOrgName()
std::string cbMySQLField::getOrgName () const
Definition at line 278 of file cbTable.cpp.
References m_orgName.
Referenced by cbMySQLField().
getOrgTable()
std::string cbMySQLField::getOrgTable () const
Definition at line 280 of file cbTable.cpp.
References m_orgTable.
Referenced by cbMySQLField().
getTable()
std::string cbMySQLField::getTable () const
Definition at line 279 of file cbTable.cpp.
References m_table.
Referenced by cbMySQLField().
setCatalog()
void cbMySQLField::setCatalog (const std::string & value)
Definition at line 296 of file cbTable.cpp.
References m_catalog.
setCharsetnr()
void cbMySQLField::setCharsetnr (int32_t value)
Definition at line 298 of file cbTable.cpp.
References m_charsetnr.
setDataType()
void cbMySQLField::setDataType (int32_t value)
Definition at line 302 of file cbTable.cpp.
References m_data_type.
setDB()
void cbMySQLField::setDB (const std::string & value)
Definition at line 295 of file cbTable.cpp.
References m_db.
setDecimals()
void cbMySQLField::setDecimals (int32_t value)
Definition at line 301 of file cbTable.cpp.
References m_decimals.
setDef()
void cbMySQLField::setDef (const std::string & value)
Definition at line 297 of file cbTable.cpp.
References m_def.
setFlags()
void cbMySQLField::setFlags (int32_t value)
Definition at line 300 of file cbTable.cpp.
References m_flags.
setLength()
void cbMySQLField::setLength (int32_t value)
Definition at line 299 of file cbTable.cpp.
References m_length.
setName()
void cbMySQLField::setName (const std::string & value)
Definition at line 291 of file cbTable.cpp.
References m_name.
setOrgName()
void cbMySQLField::setOrgName (const std::string & value)
Definition at line 292 of file cbTable.cpp.
References m_orgName.
setOrgTable()
void cbMySQLField::setOrgTable (const std::string & value)
Definition at line 294 of file cbTable.cpp.
References m_orgTable.
setTable()
void cbMySQLField::setTable (const std::string & value)
Definition at line 293 of file cbTable.cpp.
References m_table.
Referenced by cb::graph::cbComputeGraph::cbComputeGraph().
Member Data Documentation
m_catalog
std::string cbMySQLField::m_catalog private
Definition at line 455 of file cbTable.hpp.
Referenced by cbMySQLField(), getCatalog(), and setCatalog().
m_charsetnr
int cbMySQLField::m_charsetnr private
Definition at line 460 of file cbTable.hpp.
Referenced by cbMySQLField(), getCharsetnr(), and setCharsetnr().
m_data_type
int cbMySQLField::m_data_type private
Definition at line 461 of file cbTable.hpp.
Referenced by cbMySQLField(), getDataType(), and setDataType().
m_db
std::string cbMySQLField::m_db private
Definition at line 454 of file cbTable.hpp.
Referenced by cbMySQLField(), getDB(), and setDB().
m_decimals
int cbMySQLField::m_decimals private
Definition at line 459 of file cbTable.hpp.
Referenced by cbMySQLField(), getDecimals(), and setDecimals().
m_def
std::string cbMySQLField::m_def private
Definition at line 456 of file cbTable.hpp.
Referenced by cbMySQLField(), getDef(), and setDef().
m_flags
int cbMySQLField::m_flags private
Definition at line 458 of file cbTable.hpp.
Referenced by cbMySQLField(), getFlags(), and setFlags().
m_length
int cbMySQLField::m_length private
Definition at line 457 of file cbTable.hpp.
Referenced by cbMySQLField(), getLength(), and setLength().
m_name
std::string cbMySQLField::m_name private
Definition at line 450 of file cbTable.hpp.
Referenced by cbMySQLField(), getName(), and setName().
m_orgName
std::string cbMySQLField::m_orgName private
Definition at line 451 of file cbTable.hpp.
Referenced by cbMySQLField(), getOrgName(), and setOrgName().
m_orgTable
std::string cbMySQLField::m_orgTable private
Definition at line 453 of file cbTable.hpp.
Referenced by cbMySQLField(), getOrgTable(), and setOrgTable().
m_table
std::string cbMySQLField::m_table private
Definition at line 452 of file cbTable.hpp.
Referenced by cbMySQLField(), getTable(), and setTable().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbTable.hpp
/home/wang/covalentBond/src/core/server/task/cbTable.cpp