Covalent Bond: cbOpFilter Class Reference
cbOpFilter Class Reference
TODO.
#include <cbOperator.hpp>
Public Member Functions
~cbOpFilter () override
cbOpFilter ()=default
cbOpFilter (const sol::function &mapBool, const sol::function &mapLogic)
void overload (const sol::function &func) override final
void execMain () override final
void __innerFunc (baseOp *thisOp=nullptr) override final
Public Member Functions inherited from cbOpTableWise
~cbOpTableWise ()
cbOpTableWise ()
Public Member Functions inherited from baseOp
virtual ~baseOp ()
baseOp (const opType &ot)
Private Attributes
sol::function m_mapBoolFunc = sol::nil
sol::function m_mapLogicFunc = sol::nil
Additional Inherited Members
Public Attributes inherited from baseOp
cbOpIO io
opType type = opType::rowWise
bool isOverload = false
sol::function luaOverrideFunc = sol::nil
Detailed Description
TODO.
Definition at line 138 of file cbOperator.hpp.
Constructor & Destructor Documentation
~cbOpFilter()
cbOpFilter::~cbOpFilter () override
Definition at line 70 of file cbOperator.cpp.
References m_mapBoolFunc, and m_mapLogicFunc.
cbOpFilter() [1/2]
cbOpFilter::cbOpFilter () default
cbOpFilter() [2/2]
cbOpFilter::cbOpFilter (const sol::function & mapBool, const sol::function & mapLogic)
Definition at line 67 of file cbOperator.cpp.
Member Function Documentation
__innerFunc()
void cbOpFilter::__innerFunc (baseOp * thisOp = nullptr) final override virtual
Implements cbOpTableWise.
Definition at line 82 of file cbOperator.cpp.
References baseOp::isOverload, baseOp::luaOverrideFunc, m_mapBoolFunc, and m_mapLogicFunc.
Referenced by execMain().
execMain()
void cbOpFilter::execMain () final override virtual
Implements cbOpTableWise.
Definition at line 80 of file cbOperator.cpp.
References __innerFunc().
overload()
void cbOpFilter::overload (const sol::function & func) final override virtual
Implements cbOpTableWise.
Definition at line 75 of file cbOperator.cpp.
References baseOp::isOverload, and baseOp::luaOverrideFunc.
Referenced by cb::graph::cbComputeGraph::createFilterNode().
Member Data Documentation
m_mapBoolFunc
sol::function cbOpFilter::m_mapBoolFunc = sol::nil private
Definition at line 148 of file cbOperator.hpp.
Referenced by __innerFunc(), and ~cbOpFilter().
m_mapLogicFunc
sol::function cbOpFilter::m_mapLogicFunc = sol::nil private
Definition at line 149 of file cbOperator.hpp.
Referenced by __innerFunc(), and ~cbOpFilter().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbOperator.hpp
/home/wang/covalentBond/src/core/server/task/cbOperator.cpp