Covalent Bond: frontThread Class Reference
frontThread Class Reference
_WIN32
#include <liveThread.hpp>
Public Member Functions
frontThread (unsigned short httpServerPort, const std::string &name, const std::string &describe)
virtual void exec ()
Private Attributes
unsigned short m_httpServerPort = 8888
cb::utils::sysInfo m_sysInfo
trivial::cacheFile m_cacheFile
Detailed Description
_WIN32
defined(unix) && defined(clang)
Definition at line 17 of file liveThread.hpp.
Constructor & Destructor Documentation
frontThread()
frontThread::frontThread (unsigned short httpServerPort, const std::string & name, const std::string & describe) inline
Definition at line 19 of file liveThread.hpp.
References trivial::cacheFile::describe, cb::utils::getMemoryInfo(), cb::utils::getOsInfo(), m_cacheFile, cb::utils::sysInfo::m_osInfo, m_sysInfo, trivial::cacheFile::name, trivial::cacheFile::osInfo, and trivial::writeCacheFileBinary().
Member Function Documentation
exec()
void frontThread::exec () virtual
Definition at line 14 of file liveThread.cpp.
References m_httpServerPort, cb::utils::sysInfo::m_osInfo, and m_sysInfo.
Member Data Documentation
m_cacheFile
trivial::cacheFile frontThread::m_cacheFile private
Definition at line 41 of file liveThread.hpp.
Referenced by frontThread().
m_httpServerPort
unsigned short frontThread::m_httpServerPort = 8888 private
Definition at line 39 of file liveThread.hpp.
Referenced by exec().
m_sysInfo
cb::utils::sysInfo frontThread::m_sysInfo private
Definition at line 40 of file liveThread.hpp.
Referenced by exec(), and frontThread().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/liveThread.hpp
/home/wang/covalentBond/src/core/server/liveThread.cpp