Covalent Bond: cb::pipeline::app Class Reference
cb::pipeline::app Class Reference
#include <pipeline.hpp>
Public Member Functions
app (const appCfg &cfg)
void initRHttp ()
void execMain ()
void stopMain ()
Private Attributes
graphContainer m_graphs
utils::cbWebserver m_web
utils::cbRestfulHttpServer m_rHttp
trivial::cbVirtualDeviceManager m_VDM
Detailed Description
Definition at line 67 of file pipeline.hpp.
Constructor & Destructor Documentation
app()
cb::pipeline::app::app (const appCfg & cfg)
Definition at line 58 of file pipeline.cpp.
References trivial::cbVirtualDeviceManager::addRedisDevice(), trivial::cbVirtualDeviceManager::m_numsRedis, m_VDM, cb::pipeline::appCfg::redisDBNum, cb::pipeline::appCfg::redisHost, cb::pipeline::appCfg::redisPassword, cb::pipeline::appCfg::redisPort, and cb::pipeline::appCfg::redisSSL.
Member Function Documentation
execMain()
void cb::pipeline::app::execMain ()
Definition at line 157 of file pipeline.cpp.
References cb::utils::cbRestfulHttpServer::execMain(), cb::pipeline::graphContainer::execMain(), cb::utils::cbWebserver::execMain(), initRHttp(), m_graphs, m_rHttp, and m_web.
initRHttp()
void cb::pipeline::app::initRHttp ()
add_graph. POST. type: APPLICATION_JSON id: the index of the graph. script: the script that create the graph.
Note
curl -H "Content-Type: application/json" -X POST -d "{\"id": 0, "script": "I am
iron man"}" "http://localhost:8080/add_graph"
first: the output structure. second: true data
Definition at line 68 of file pipeline.cpp.
References cb::apiCPP::addGraph(), cb::pipeline::graphContainer::addGraph(), trivial::cbVirtualDeviceManager::addMySqlDevice(), cb::pipeline::graphContainer::getGraph(), cb::graph::cbComputeGraph::getOutput(), m_graphs, trivial::cbVirtualDeviceManager::m_numsMySql, m_rHttp, cbOutputTableStruct::m_shape, and m_VDM.
Referenced by execMain().
stopMain()
void cb::pipeline::app::stopMain ()
Definition at line 167 of file pipeline.cpp.
References m_graphs, m_rHttp, m_web, cb::pipeline::graphContainer::setTerminated(), cb::utils::cbRestfulHttpServer::stopMain(), and cb::utils::cbWebserver::stopMain().
Member Data Documentation
m_graphs
graphContainer cb::pipeline::app::m_graphs private
Definition at line 90 of file pipeline.hpp.
Referenced by execMain(), initRHttp(), and stopMain().
m_rHttp
utils::cbRestfulHttpServer cb::pipeline::app::m_rHttp private
Definition at line 92 of file pipeline.hpp.
Referenced by execMain(), initRHttp(), and stopMain().
m_VDM
trivial::cbVirtualDeviceManager cb::pipeline::app::m_VDM private
Definition at line 93 of file pipeline.hpp.
Referenced by app(), and initRHttp().
m_web
utils::cbWebserver cb::pipeline::app::m_web private
Definition at line 91 of file pipeline.hpp.
Referenced by execMain(), and stopMain().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/pipeline.hpp
/home/wang/covalentBond/src/core/server/pipeline.cpp