Covalent Bond: cb::graph::cbComputeGraph Class Reference
cb::graph::cbComputeGraph Class Reference
#include <cbComputeGraph.hpp>
Public Member Functions
cbComputeGraph (int32_t idx)
~cbComputeGraph ()
bool isDAG ()
To judge the Graph is DAG or not.
bool isSingleOutput ()
To judge the graph has single output or not.
cbMySQLCell * createCell ()
Create a Cell object.
cbMySQLCell * createCell (int value)
Create a Cell object.
cbMySQLCell * createCell (float value)
Create a Cell object.
cbMySQLCell * createCell (double value)
Create a Cell object.
cbMySQLCell * createCell (unsigned long long value)
Create a Cell object.
cbMySQLCell * createCell (const std::string &value)
Create a Cell object.
cbMySQLCell * createCell (const std::string &value, const cbMySQLType &t)
Create a Cell object.
cbVirtualDeviceNode * createVirtualDeviceNode (int32_t idx)
create nodes belongs to this graph.
cbRedisCachingNode * createRedisCachingNode (int32_t idx)
! for sql only, now.
cbOperatorNode * createCombineNode (const std::vector< std::string > &keys, const std::string &name)
Create a Combine Node object.
void setVirtualDeviceManager (trivial::cbVirtualDeviceManager *virtualDeviceM)
Set the Virtual Device Manager object.
void registerNode (cbNode *node)
register a node. Not used by lua binding.
int32_t getId ()
Get the Id object.
WFGraphTask * generateGraphTask (const graph_callback &func=nullptr)
Create the graph task.
void execScriptFile (const std::string &filePath)
execute the script from file.
void execScript (const std::string &script)
execute the script
void addCacheServer (cbRedisCachingNode *v)
The cache server node. Lua binding in.
cbOutputTableStruct * getOutput ()
Get the Output object.
std::vector< cbNode * > getNodes ()
Get the Nodes object.
Static Public Member Functions
static void execMain (WFGraphTask *task, cbComputeGraph *graph)
Execute the graph task.
Public Attributes
friend cbVirtualDeviceNode
friend cbRedisCachingNode
friend cbOperatorNode
Private Attributes
int32_t m_idx = 0
cbOpIO io
std::vector< cbNode * > m_nodes
cbRedisCachingNode * m_cacheNode = nullptr
cbGraphSharedMem * m_sharedMem = nullptr
cbGraphSharedLuaStack * m_sharedLuaStack = nullptr
trivial::cbVirtualDeviceManager * m_virtualDevice = nullptr
Detailed Description
Definition at line 342 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
cbComputeGraph()
cb::graph::cbComputeGraph::cbComputeGraph (int32_t idx)
Definition at line 171 of file cbComputeGraph.cpp.
References __luaPackedCellAsVec(), __luaPackedStringAsVec(), addCacheServer(), cb::graph::cbVirtualDeviceNode::addQuery(), cbVirtualTable::atPtr(), cbVirtualTable::atPtrRef(), cbVirtualTable::colNameAt(), cbVirtualTable::colTypeAt(), createCell(), createCombineNode(), createRedisCachingNode(), createVirtualDeviceNode(), DataTime, Date, Double, fetchShapeIndex(), Float, cb::graph::cbGraphSharedLuaStack::get(), cbVirtualTable::getCol(), cbVirtualTable::getInfoAt(), cbVirtualTable::getRow(), cbVirtualTable::getShape(), cbOpIO::I, Int, baseOp::io, cb::graph::cbNode::io, isDAG(), isSingleOutput(), cbVirtualTable::keyBy(), m_sharedLuaStack, MAKE_SHARED, Null, cbOpIO::O, cb::graph::cbOperatorNode::Op, cbOpCombine::overload(), cb::graph::cbNode::PointTo(), cbVirtualTable::pushRow(), cbVirtualTable::resetShape(), cbVirtualTable::resetShapeH(), cbVirtualTable::setInfoAt(), cbVirtualTable::setPtrAt(), cbMySQLField::setTable(), storeShapeIndex(), cbVirtualTable::str(), String, Time, and ULL.
~cbComputeGraph()
cb::graph::cbComputeGraph::~cbComputeGraph ()
Definition at line 362 of file cbComputeGraph.cpp.
References m_nodes, m_sharedLuaStack, and m_sharedMem.
Member Function Documentation
addCacheServer()
void cb::graph::cbComputeGraph::addCacheServer (cbRedisCachingNode * v)
The cache server node. Lua binding in.
Parameters
v the redis caching server node.
Definition at line 556 of file cbComputeGraph.cpp.
References cb::graph::cbNode::graph, and m_cacheNode.
Referenced by cbComputeGraph().
createCell() [1/7]
cbMySQLCell * cb::graph::cbComputeGraph::createCell ()
Create a Cell object.
Returns
cbMySQLCell*
Definition at line 393 of file cbComputeGraph.cpp.
References m_sharedMem, and cb::graph::cbGraphSharedMem::push().
Referenced by cbComputeGraph().
createCell() [2/7]
cbMySQLCell * cb::graph::cbComputeGraph::createCell (const std::string & value)
Create a Cell object.
Parameters
value string
Returns
cbMySQLCell*
Definition at line 423 of file cbComputeGraph.cpp.
References m_sharedMem, and cb::graph::cbGraphSharedMem::push().
createCell() [3/7]
cbMySQLCell * cb::graph::cbComputeGraph::createCell (const std::string & value, const cbMySQLType & t)
Create a Cell object.
Parameters
value string
t the type. such as String, Date, DateTime.
Returns
cbMySQLCell*
Definition at line 429 of file cbComputeGraph.cpp.
References m_sharedMem, and cb::graph::cbGraphSharedMem::push().
createCell() [4/7]
cbMySQLCell * cb::graph::cbComputeGraph::createCell (double value)
Create a Cell object.
Parameters
value double
Returns
cbMySQLCell*
Definition at line 411 of file cbComputeGraph.cpp.
References m_sharedMem, and cb::graph::cbGraphSharedMem::push().
createCell() [5/7]
cbMySQLCell * cb::graph::cbComputeGraph::createCell (float value)
Create a Cell object.
Parameters
value float
Returns
cbMySQLCell*
Definition at line 405 of file cbComputeGraph.cpp.
References m_sharedMem, and cb::graph::cbGraphSharedMem::push().
createCell() [6/7]
cbMySQLCell * cb::graph::cbComputeGraph::createCell (int value)
Create a Cell object.
Parameters
value int
Returns
cbMySQLCell*
Definition at line 399 of file cbComputeGraph.cpp.
References m_sharedMem, and cb::graph::cbGraphSharedMem::push().
createCell() [7/7]
cbMySQLCell * cb::graph::cbComputeGraph::createCell (unsigned long long value)
Create a Cell object.
Parameters
value unsigned long long
Returns
cbMySQLCell*
Definition at line 417 of file cbComputeGraph.cpp.
References m_sharedMem, and cb::graph::cbGraphSharedMem::push().
createCombineNode()
cbOperatorNode * cb::graph::cbComputeGraph::createCombineNode (const std::vector< std::string > & keys, const std::string & name)
Create a Combine Node object.
Parameters
keys
name
Returns
cbOperatorNode*
Definition at line 448 of file cbComputeGraph.cpp.
References cbOperatorNode, cb::graph::cbGraphSharedLuaStack::get(), m_sharedLuaStack, cbOpCombine::overload(), and registerNode().
Referenced by cbComputeGraph().
createRedisCachingNode()
cbRedisCachingNode * cb::graph::cbComputeGraph::createRedisCachingNode (int32_t idx)
! for sql only, now.
Create a Redis Caching Node object
Parameters
idx
Returns
cbRedisCachingNode*
Definition at line 442 of file cbComputeGraph.cpp.
References cbRedisCachingNode, trivial::cbVirtualDeviceManager::getRedisDevice(), m_virtualDevice, and cb::graph::cbRedisCachingNode::setRedisDevice().
Referenced by cbComputeGraph().
createVirtualDeviceNode()
cbVirtualDeviceNode * cb::graph::cbComputeGraph::createVirtualDeviceNode (int32_t idx)
create nodes belongs to this graph.
Parameters
idx
Returns
cbVirtualDeviceNode*
Definition at line 435 of file cbComputeGraph.cpp.
References cbVirtualDeviceNode, trivial::cbVirtualDeviceManager::getMySqlDevice(), m_virtualDevice, registerNode(), and cb::graph::cbVirtualDeviceNode::setMySQLDevice().
Referenced by cbComputeGraph().
execMain()
void cb::graph::cbComputeGraph::execMain (WFGraphTask * task, cbComputeGraph * graph) static
Execute the graph task.
Parameters
task
graph
Definition at line 540 of file cbComputeGraph.cpp.
execScript()
void cb::graph::cbComputeGraph::execScript (const std::string & script)
execute the script
Parameters
script
Definition at line 554 of file cbComputeGraph.cpp.
References cb::graph::cbGraphSharedLuaStack::execScript(), and m_sharedLuaStack.
Referenced by cb::apiCPP::addGraph().
execScriptFile()
void cb::graph::cbComputeGraph::execScriptFile (const std::string & filePath)
execute the script from file.
Parameters
filePath
Definition at line 550 of file cbComputeGraph.cpp.
References cb::graph::cbGraphSharedLuaStack::execScriptFile(), and m_sharedLuaStack.
generateGraphTask()
WFGraphTask * cb::graph::cbComputeGraph::generateGraphTask (const graph_callback & func = nullptr)
Create the graph task.
Parameters
func
Returns
WFGraphTask*
Definition at line 470 of file cbComputeGraph.cpp.
References cb::graph::cbRedisCachingNode::_generateSetTask(), cbVirtualTable::atPtr(), cb::graph::cbGraphSharedMem::clear(), cb::graph::cbGraphSharedMem::getOutStruct(), io, isDAG(), isSingleOutput(), cb::graph::Leaf, m_cacheNode, m_idx, m_nodes, cbOutputTableStruct::m_shape, m_sharedMem, cbOpIO::O, cb::graph::Operator, and cb::graph::Output.
getId()
int32_t cb::graph::cbComputeGraph::getId ()
Get the Id object.
Returns
int32_t
Definition at line 468 of file cbComputeGraph.cpp.
References m_idx.
getNodes()
std::vector< cbNode * > cb::graph::cbComputeGraph::getNodes ()
Get the Nodes object.
Returns
std::vector<cbNode*>
Definition at line 563 of file cbComputeGraph.cpp.
References m_nodes.
getOutput()
cbOutputTableStruct * cb::graph::cbComputeGraph::getOutput ()
Get the Output object.
Returns
cbOutputTableStruct*
Definition at line 561 of file cbComputeGraph.cpp.
References cb::graph::cbGraphSharedMem::getOutStruct(), and m_sharedMem.
Referenced by cb::pipeline::app::initRHttp().
isDAG()
bool cb::graph::cbComputeGraph::isDAG ()
To judge the Graph is DAG or not.
Returns
true
false
Definition at line 368 of file cbComputeGraph.cpp.
References isSingleOutput(), m_nodes, and cb::graph::cbNode::nextNode.
Referenced by cbComputeGraph(), and generateGraphTask().
isSingleOutput()
bool cb::graph::cbComputeGraph::isSingleOutput ()
To judge the graph has single output or not.
Returns
true
false
Definition at line 382 of file cbComputeGraph.cpp.
References m_nodes.
Referenced by cbComputeGraph(), generateGraphTask(), and isDAG().
registerNode()
void cb::graph::cbComputeGraph::registerNode (cbNode * node)
register a node. Not used by lua binding.
Parameters
node
Definition at line 463 of file cbComputeGraph.cpp.
References m_nodes.
Referenced by createCombineNode(), and createVirtualDeviceNode().
setVirtualDeviceManager()
void cb::graph::cbComputeGraph::setVirtualDeviceManager (trivial::cbVirtualDeviceManager * virtualDeviceM)
Set the Virtual Device Manager object.
Parameters
virtualDeviceM
Definition at line 459 of file cbComputeGraph.cpp.
References m_virtualDevice.
Referenced by cb::apiCPP::addGraph().
Member Data Documentation
cbOperatorNode
friend cb::graph::cbComputeGraph::cbOperatorNode
Definition at line 346 of file cbComputeGraph.hpp.
Referenced by createCombineNode().
cbRedisCachingNode
friend cb::graph::cbComputeGraph::cbRedisCachingNode
Definition at line 345 of file cbComputeGraph.hpp.
Referenced by createRedisCachingNode().
cbVirtualDeviceNode
friend cb::graph::cbComputeGraph::cbVirtualDeviceNode
Definition at line 344 of file cbComputeGraph.hpp.
Referenced by createVirtualDeviceNode().
io
cbOpIO cb::graph::cbComputeGraph::io private
Definition at line 523 of file cbComputeGraph.hpp.
Referenced by generateGraphTask(), and cb::graph::cbVirtualDeviceNode::generateTask().
m_cacheNode
cbRedisCachingNode* cb::graph::cbComputeGraph::m_cacheNode = nullptr private
Definition at line 525 of file cbComputeGraph.hpp.
Referenced by addCacheServer(), and generateGraphTask().
m_idx
int32_t cb::graph::cbComputeGraph::m_idx = 0 private
Definition at line 522 of file cbComputeGraph.hpp.
Referenced by generateGraphTask(), and getId().
m_nodes
std::vector<cbNode*> cb::graph::cbComputeGraph::m_nodes private
Definition at line 524 of file cbComputeGraph.hpp.
Referenced by generateGraphTask(), getNodes(), isDAG(), isSingleOutput(), registerNode(), and ~cbComputeGraph().
m_sharedLuaStack
cbGraphSharedLuaStack* cb::graph::cbComputeGraph::m_sharedLuaStack = nullptr private
Definition at line 527 of file cbComputeGraph.hpp.
Referenced by cbComputeGraph(), createCombineNode(), execScript(), execScriptFile(), and ~cbComputeGraph().
m_sharedMem
cbGraphSharedMem* cb::graph::cbComputeGraph::m_sharedMem = nullptr private
Definition at line 526 of file cbComputeGraph.hpp.
Referenced by createCell(), generateGraphTask(), cb::graph::cbVirtualDeviceNode::generateTask(), getOutput(), and ~cbComputeGraph().
m_virtualDevice
trivial::cbVirtualDeviceManager* cb::graph::cbComputeGraph::m_virtualDevice = nullptr private
Definition at line 529 of file cbComputeGraph.hpp.
Referenced by createRedisCachingNode(), createVirtualDeviceNode(), and setVirtualDeviceManager().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp