Covalent Bond: cbTable Class Reference
cbTable Class Reference
#include <cbTable.hpp>
Public Member Functions
cbTable ()=delete
cbTable (const cbTable &rhs)
cbTable (cbShape< 2 > &shape)
cbTable (cbShape< 2 > &shape, cbCell *dataptr)
void setThisAsTrueDataContainer ()
cbCell * at (int32_t i, int32_t j)
cbCell * operator() (int32_t i, int32_t j)
cbTable operator() (const std::pair< int32_t, int32_t > &row_i, const cbTableSlice &cbSl)
cbTableRow getRow (int32_t i)
cbTableCol getCol (int32_t i)
Public Member Functions inherited from __metaMatrix< 2 >
__metaMatrix ()=default
__metaMatrix (const cbShape< Dims > &shape)
__metaMatrix (const cbShape< Dims > &shape, cbCell *dataptr)
__metaMatrix (const __metaMatrix &rhs)
void free ()
Public Attributes
cbTableHead head
Public Attributes inherited from __metaMatrix< 2 >
cbShape< Dims > m_shape
cbCell * __dataptr
bool m_trueDataContainer
Private Attributes
int32_t m_stride = 0
Detailed Description
Definition at line 283 of file cbTable.hpp.
Constructor & Destructor Documentation
cbTable() [1/4]
cbTable::cbTable () delete
cbTable() [2/4]
cbTable::cbTable (const cbTable & rhs) inline
Definition at line 286 of file cbTable.hpp.
References __metaMatrix< 2 >::__dataptr, __metaMatrix< Dims >::__dataptr, __metaMatrix< Dims >::m_shape, __metaMatrix< 2 >::m_shape, and m_stride.
cbTable() [3/4]
cbTable::cbTable (cbShape< 2 > & shape) inline
Definition at line 291 of file cbTable.hpp.
cbTable() [4/4]
cbTable::cbTable (cbShape< 2 > & shape, cbCell * dataptr) inline
Definition at line 292 of file cbTable.hpp.
Member Function Documentation
at()
cbCell* cbTable::at (int32_t i, int32_t j) inline
Definition at line 297 of file cbTable.hpp.
References __metaMatrix< 2 >::__dataptr, and m_stride.
Referenced by operator()().
getCol()
cbTableCol cbTable::getCol (int32_t i) inline
Definition at line 323 of file cbTable.hpp.
References __metaMatrix< 2 >::__dataptr, cbTableCol::head, head, __metaMatrix< 2 >::m_shape, m_stride, makeShapeCol(), and cbTableHead::set().
getRow()
cbTableRow cbTable::getRow (int32_t i) inline
Definition at line 317 of file cbTable.hpp.
References __metaMatrix< 2 >::__dataptr, cbTableRow::head, head, __metaMatrix< 2 >::m_shape, m_stride, and makeShapeRow().
operator()() [1/2]
cbTable cbTable::operator() (const std::pair< int32_t, int32_t > & row_i, const cbTableSlice & cbSl) inline
Definition at line 301 of file cbTable.hpp.
References __metaMatrix< 2 >::__dataptr, all, head, __metaMatrix< 2 >::m_shape, makeShapeFull(), no, and seq.
operator()() [2/2]
cbCell* cbTable::operator() (int32_t i, int32_t j) inline
Definition at line 299 of file cbTable.hpp.
References at().
setThisAsTrueDataContainer()
void cbTable::setThisAsTrueDataContainer () inline
Definition at line 295 of file cbTable.hpp.
References __metaMatrix< 2 >::m_trueDataContainer.
Referenced by mallocMetaMatrix().
Member Data Documentation
head
cbTableHead cbTable::head
Definition at line 332 of file cbTable.hpp.
Referenced by getCol(), getRow(), and operator()().
m_stride
int32_t cbTable::m_stride = 0 private
Definition at line 335 of file cbTable.hpp.
Referenced by at(), cbTable(), getCol(), and getRow().
The documentation for this class was generated from the following file:
/home/wang/covalentBond/src/core/server/task/cbTable.hpp