Covalent Bond: cb::cbLRUCache< V > Class Template Reference
cb::cbLRUCache< V > Class Template Reference
We used LRU alogrithm to implement our cache.
#include <cbLRUCache.hpp>
Public Member Functions
cbLRUCache (int32_t max_size)
Construct a new cb Least Recently Use Cache object.
~cbLRUCache ()
Destroy the cb Least Recently Use Cache object.
void push (std::string key, V value)
Push key and value into cache. If key has been existed, the corresponding value will be update.
V * get (const std::string &key)
Get the value of corresponding key of input, if key doesn't exist, it will return null pointer.
Private Member Functions
void eraseTail ()
delete the last element of list
void update (const std::string &key)
move the node has been used recently to the top of cache list
void insertTop (const std::string &key)
transit the node choosen to the top of list
void __loop_map ()
loop in cachae list and map
Private Attributes
int32_t m_maxSize
int32_t m_sizeCounter
node * m_bufNode
std::string m_bufKey
std::list< node > m_cacheList
std::map< std::string, V > m_cacheMap
Detailed Description
template<typename V>
class cb::cbLRUCache< V >
We used LRU alogrithm to implement our cache.
Template Parameters
V You can set any type of value and key only support string
Definition at line 39 of file cbLRUCache.hpp.
Constructor & Destructor Documentation
cbLRUCache()
template<typename V > cb::cbLRUCache< V >::cbLRUCache (int32_t max_size) inline
Construct a new cb Least Recently Use Cache object.
Parameters
max_size Maximum sixe of cache
Definition at line 46 of file cbLRUCache.hpp.
~cbLRUCache()
template<typename V > cb::cbLRUCache< V >::~cbLRUCache () inline
Destroy the cb Least Recently Use Cache object.
Definition at line 52 of file cbLRUCache.hpp.
References cb::cbLRUCache< V >::m_bufNode.
Member Function Documentation
__loop_map()
template<typename V > void cb::cbLRUCache< V >::__loop_map () inline private
loop in cachae list and map
Definition at line 144 of file cbLRUCache.hpp.
References cb::cbLRUCache< V >::m_cacheList, and cb::cbLRUCache< V >::m_cacheMap.
eraseTail()
template<typename V > void cb::cbLRUCache< V >::eraseTail () inline private
delete the last element of list
Definition at line 103 of file cbLRUCache.hpp.
References cb::listNode::key, cb::cbLRUCache< V >::m_bufKey, cb::cbLRUCache< V >::m_bufNode, cb::cbLRUCache< V >::m_cacheList, and cb::cbLRUCache< V >::m_cacheMap.
Referenced by cb::cbLRUCache< V >::push().
get()
template<typename V > V* cb::cbLRUCache< V >::get (const std::string & key) inline
Get the value of corresponding key of input, if key doesn't exist, it will return null pointer.
Parameters
key key of cache map
Returns
V* the pointer of type V
Definition at line 86 of file cbLRUCache.hpp.
References cb::cbLRUCache< V >::m_cacheMap, and cb::cbLRUCache< V >::update().
insertTop()
template<typename V > void cb::cbLRUCache< V >::insertTop (const std::string & key) inline private
transit the node choosen to the top of list
Parameters
key key of cache map
Definition at line 132 of file cbLRUCache.hpp.
References cb::listNode::key, cb::cbLRUCache< V >::m_bufNode, and cb::cbLRUCache< V >::m_cacheList.
Referenced by cb::cbLRUCache< V >::push(), and cb::cbLRUCache< V >::update().
push()
template<typename V > void cb::cbLRUCache< V >::push (std::string key, V value) inline
Push key and value into cache. If key has been existed, the corresponding value will be update.
Parameters
key key of cache map
value value of cache map
Definition at line 61 of file cbLRUCache.hpp.
References cb::cbLRUCache< V >::eraseTail(), find_list, cb::cbLRUCache< V >::insertTop(), cb::cbLRUCache< V >::m_cacheMap, cb::cbLRUCache< V >::m_maxSize, cb::cbLRUCache< V >::m_sizeCounter, and cb::cbLRUCache< V >::update().
update()
template<typename V > void cb::cbLRUCache< V >::update (const std::string & key) inline private
move the node has been used recently to the top of cache list
Parameters
key key of cache map
Definition at line 117 of file cbLRUCache.hpp.
References find_list, cb::cbLRUCache< V >::insertTop(), and cb::cbLRUCache< V >::m_cacheList.
Referenced by cb::cbLRUCache< V >::get(), and cb::cbLRUCache< V >::push().
Member Data Documentation
m_bufKey
template<typename V > std::string cb::cbLRUCache< V >::m_bufKey private
Definition at line 158 of file cbLRUCache.hpp.
Referenced by cb::cbLRUCache< V >::eraseTail().
m_bufNode
template<typename V > node* cb::cbLRUCache< V >::m_bufNode private
Definition at line 157 of file cbLRUCache.hpp.
Referenced by cb::cbLRUCache< V >::eraseTail(), cb::cbLRUCache< V >::insertTop(), and cb::cbLRUCache< V >::~cbLRUCache().
m_cacheList
template<typename V > std::list<node> cb::cbLRUCache< V >::m_cacheList private
Definition at line 159 of file cbLRUCache.hpp.
Referenced by cb::cbLRUCache< V >::__loop_map(), cb::cbLRUCache< V >::eraseTail(), cb::cbLRUCache< V >::insertTop(), and cb::cbLRUCache< V >::update().
m_cacheMap
template<typename V > std::map<std::string, V> cb::cbLRUCache< V >::m_cacheMap private
Definition at line 160 of file cbLRUCache.hpp.
Referenced by cb::cbLRUCache< V >::__loop_map(), cb::cbLRUCache< V >::eraseTail(), cb::cbLRUCache< V >::get(), and cb::cbLRUCache< V >::push().
m_maxSize
template<typename V > int32_t cb::cbLRUCache< V >::m_maxSize private
Definition at line 155 of file cbLRUCache.hpp.
Referenced by cb::cbLRUCache< V >::push().
m_sizeCounter
template<typename V > int32_t cb::cbLRUCache< V >::m_sizeCounter private
Definition at line 156 of file cbLRUCache.hpp.
Referenced by cb::cbLRUCache< V >::push().
The documentation for this class was generated from the following file:
/home/wang/covalentBond/src/core/server/mem/cbLRUCache.hpp