Covalent Bond: cbOpCombine Class Reference
cbOpCombine Class Reference final
#include <cbOperator.hpp>
Public Member Functions
~cbOpCombine () override
cbOpCombine (const std::vector< std::string > &key, const std::string name)
void overload (const sol::function &func) override final
void execMain () override final
void __innerFunc (baseOp *thisOp=nullptr) override final
Public Member Functions inherited from cbOpRowWise
~cbOpRowWise ()
cbOpRowWise ()
Public Member Functions inherited from baseOp
virtual ~baseOp ()
baseOp (const opType &ot)
Private Attributes
const std::string m_tableName
const std::vector< std::string > m_key
Additional Inherited Members
Public Attributes inherited from baseOp
cbOpIO io
opType type = opType::rowWise
bool isOverload = false
sol::function luaOverrideFunc = sol::nil
Detailed Description
Definition at line 108 of file cbOperator.hpp.
Constructor & Destructor Documentation
~cbOpCombine()
cbOpCombine::~cbOpCombine () override
Definition at line 29 of file cbOperator.cpp.
cbOpCombine()
cbOpCombine::cbOpCombine (const std::vector< std::string > & key, const std::string name)
Definition at line 31 of file cbOperator.cpp.
Member Function Documentation
__innerFunc()
void cbOpCombine::__innerFunc (baseOp * thisOp = nullptr) final override virtual
Implements cbOpRowWise.
Definition at line 41 of file cbOperator.cpp.
References baseOp::isOverload, baseOp::luaOverrideFunc, m_key, and m_tableName.
Referenced by execMain().
execMain()
void cbOpCombine::execMain () final override virtual
Implements cbOpRowWise.
Definition at line 39 of file cbOperator.cpp.
References __innerFunc().
overload()
void cbOpCombine::overload (const sol::function & func) final override virtual
Implements cbOpRowWise.
Definition at line 34 of file cbOperator.cpp.
References baseOp::isOverload, and baseOp::luaOverrideFunc.
Referenced by cb::graph::cbComputeGraph::cbComputeGraph(), and cb::graph::cbComputeGraph::createCombineNode().
Member Data Documentation
m_key
const std::vector<std::string> cbOpCombine::m_key private
Definition at line 118 of file cbOperator.hpp.
Referenced by __innerFunc().
m_tableName
const std::string cbOpCombine::m_tableName private
Definition at line 117 of file cbOperator.hpp.
Referenced by __innerFunc().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbOperator.hpp
/home/wang/covalentBond/src/core/server/task/cbOperator.cpp