Covalent Bond: cb::pipeline::graphContainer Class Reference
cb::pipeline::graphContainer Class Reference
#include <pipeline.hpp>
Public Member Functions
~graphContainer ()
graphContainer (int32_t n)
graphContainer (graphContainer &)=delete
graphContainer (const graphContainer &)=delete
graphContainer operator= (graphContainer &)=delete
graphContainer operator= (const graphContainer &)=delete
void addGraph (graph::cbComputeGraph *g)
graph::cbComputeGraph * getGraph (int32_t idx)
void execMain ()
void setTerminated (bool enable)
Private Attributes
bool m_isTerminated = false
std::vector< graph::cbComputeGraph * > m_graphs
int32_t m_loopTime = 10
Detailed Description
Definition at line 35 of file pipeline.hpp.
Constructor & Destructor Documentation
~graphContainer()
cb::pipeline::graphContainer::~graphContainer ()
Definition at line 13 of file pipeline.cpp.
References m_graphs.
graphContainer() [1/3]
cb::pipeline::graphContainer::graphContainer (int32_t n)
Definition at line 11 of file pipeline.cpp.
graphContainer() [2/3]
cb::pipeline::graphContainer::graphContainer (graphContainer &) delete
graphContainer() [3/3]
cb::pipeline::graphContainer::graphContainer (const graphContainer &) delete
Member Function Documentation
addGraph()
void cb::pipeline::graphContainer::addGraph (graph::cbComputeGraph * g)
Definition at line 17 of file pipeline.cpp.
References m_graphs.
Referenced by cb::pipeline::app::initRHttp().
execMain()
void cb::pipeline::graphContainer::execMain ()
Definition at line 26 of file pipeline.cpp.
References m_graphs, m_isTerminated, and m_loopTime.
Referenced by cb::pipeline::app::execMain().
getGraph()
graph::cbComputeGraph * cb::pipeline::graphContainer::getGraph (int32_t idx)
Definition at line 19 of file pipeline.cpp.
References m_graphs.
Referenced by cb::pipeline::app::initRHttp().
operator=() [1/2]
graphContainer cb::pipeline::graphContainer::operator= (const graphContainer &) delete
operator=() [2/2]
graphContainer cb::pipeline::graphContainer::operator= (graphContainer &) delete
setTerminated()
void cb::pipeline::graphContainer::setTerminated (bool enable)
Definition at line 56 of file pipeline.cpp.
References m_isTerminated.
Referenced by cb::pipeline::app::stopMain().
Member Data Documentation
m_graphs
std::vector<graph::cbComputeGraph*> cb::pipeline::graphContainer::m_graphs private
Definition at line 51 of file pipeline.hpp.
Referenced by addGraph(), execMain(), getGraph(), and ~graphContainer().
m_isTerminated
bool cb::pipeline::graphContainer::m_isTerminated = false private
Definition at line 50 of file pipeline.hpp.
Referenced by execMain(), and setTerminated().
m_loopTime
int32_t cb::pipeline::graphContainer::m_loopTime = 10 private
Definition at line 52 of file pipeline.hpp.
Referenced by execMain().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/pipeline.hpp
/home/wang/covalentBond/src/core/server/pipeline.cpp