Covalent Bond: graph::cbComputeGraph Class Reference
graph::cbComputeGraph Class Reference
#include <cbComputeGraph.hpp>
Public Member Functions
cbComputeGraph (int32_t idx)
~cbComputeGraph ()
bool isDAG ()
To judge the Graph is DAG or not.
bool isSingleOutput ()
To judge the graph has single output or not.
cbMySQLCell * createCell ()
Create a Cell object.
cbMySQLCell * createCell (int value)
Create a Cell object.
cbMySQLCell * createCell (float value)
Create a Cell object.
cbMySQLCell * createCell (double value)
Create a Cell object.
cbMySQLCell * createCell (unsigned long long value)
Create a Cell object.
cbMySQLCell * createCell (const std::string &value)
Create a Cell object.
cbMySQLCell * createCell (const std::string &value, const cbMySQLType &t)
Create a Cell object.
cbVirtualDeviceNode * createVirtualDeviceNode (int32_t idx)
create nodes belongs to this graph.
cbOperatorNode * createCombineNode (const std::vector< std::string > &keys)
! for sql only, now.
void setVirtualDeviceManager (trivial::cbVirtualDeviceManager *virtualDeviceM)
Set the Virtual Device Manager object.
void registerNode (cbNode *node)
register a node. Not used by lua binding.
int32_t getId ()
Get the Id object.
WFGraphTask * generateGraphTask (const graph_callback &func=nullptr)
Create the graph task.
void execScriptFile (const std::string &filePath)
execute the script from file.
void execScript (const std::string &script)
execute the script
Static Public Member Functions
static void execMain (WFGraphTask *task, cbComputeGraph *graph)
Execute the graph task.
Public Attributes
friend cbVirtualDeviceNode
Private Attributes
int32_t m_idx = 0
std::vector< cbNode * > m_nodes
cbGraphSharedMem * m_sharedMem = nullptr
cbGraphSharedLuaStack * m_sharedLuaStack = nullptr
WFFacilities::WaitGroup m_waitGroup
trivial::cbVirtualDeviceManager * m_virtualDevice = nullptr
Detailed Description
Definition at line 192 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
cbComputeGraph()
graph::cbComputeGraph::cbComputeGraph (int32_t idx)
Definition at line 120 of file cbComputeGraph.cpp.
References __luaPackedCellAsVec(), __luaPackedStringAsVec(), graph::cbVirtualDeviceNode::addQuery(), cbVirtualTable::atPtrRef(), cbVirtualTable::colNameAt(), cbVirtualTable::colTypeAt(), createCell(), createCombineNode(), createVirtualDeviceNode(), fetchShapeIndex(), graph::cbGraphSharedLuaStack::get(), cbVirtualTable::getCol(), cbVirtualTable::getRow(), cbVirtualTable::getShape(), cbOpIO::I, graph::cbNode::io, isDAG(), isSingleOutput(), cbVirtualTable::keyBy(), m_sharedLuaStack, cbOpIO::O, graph::cbNode::PointTo(), cbVirtualTable::pushRow(), cbVirtualTable::resetShape(), and storeShapeIndex().
~cbComputeGraph()
graph::cbComputeGraph::~cbComputeGraph ()
Definition at line 253 of file cbComputeGraph.cpp.
References m_nodes, m_sharedLuaStack, and m_sharedMem.
Member Function Documentation
createCell() [1/7]
cbMySQLCell * graph::cbComputeGraph::createCell ()
Create a Cell object.
Returns
cbMySQLCell*
Definition at line 281 of file cbComputeGraph.cpp.
References m_sharedMem, and graph::cbGraphSharedMem::push().
Referenced by cbComputeGraph().
createCell() [2/7]
cbMySQLCell * graph::cbComputeGraph::createCell (const std::string & value)
Create a Cell object.
Parameters
value string
Returns
cbMySQLCell*
Definition at line 311 of file cbComputeGraph.cpp.
References m_sharedMem, and graph::cbGraphSharedMem::push().
createCell() [3/7]
cbMySQLCell * graph::cbComputeGraph::createCell (const std::string & value, const cbMySQLType & t)
Create a Cell object.
Parameters
value string
t the type. such as String, Date, DateTime.
Returns
cbMySQLCell*
Definition at line 317 of file cbComputeGraph.cpp.
References m_sharedMem, and graph::cbGraphSharedMem::push().
createCell() [4/7]
cbMySQLCell * graph::cbComputeGraph::createCell (double value)
Create a Cell object.
Parameters
value double
Returns
cbMySQLCell*
Definition at line 299 of file cbComputeGraph.cpp.
References m_sharedMem, and graph::cbGraphSharedMem::push().
createCell() [5/7]
cbMySQLCell * graph::cbComputeGraph::createCell (float value)
Create a Cell object.
Parameters
value float
Returns
cbMySQLCell*
Definition at line 293 of file cbComputeGraph.cpp.
References m_sharedMem, and graph::cbGraphSharedMem::push().
createCell() [6/7]
cbMySQLCell * graph::cbComputeGraph::createCell (int value)
Create a Cell object.
Parameters
value int
Returns
cbMySQLCell*
Definition at line 287 of file cbComputeGraph.cpp.
References m_sharedMem, and graph::cbGraphSharedMem::push().
createCell() [7/7]
cbMySQLCell * graph::cbComputeGraph::createCell (unsigned long long value)
Create a Cell object.
Parameters
value unsigned long long
Returns
cbMySQLCell*
Definition at line 305 of file cbComputeGraph.cpp.
References m_sharedMem, and graph::cbGraphSharedMem::push().
createCombineNode()
cbOperatorNode * graph::cbComputeGraph::createCombineNode (const std::vector< std::string > & keys)
! for sql only, now.
Create a Combine Node object
Parameters
keys
Returns
cbOperatorNode*
Definition at line 330 of file cbComputeGraph.cpp.
References registerNode().
Referenced by cbComputeGraph().
createVirtualDeviceNode()
cbVirtualDeviceNode * graph::cbComputeGraph::createVirtualDeviceNode (int32_t idx)
create nodes belongs to this graph.
Parameters
idx
Returns
cbVirtualDeviceNode*
Definition at line 323 of file cbComputeGraph.cpp.
References cbVirtualDeviceNode, trivial::cbVirtualDeviceManager::getMySqlDevice(), m_virtualDevice, registerNode(), and graph::cbVirtualDeviceNode::setMySQLDevice().
Referenced by cbComputeGraph().
execMain()
void graph::cbComputeGraph::execMain (WFGraphTask * task, cbComputeGraph * graph) static
Execute the graph task.
Parameters
task
graph
Definition at line 376 of file cbComputeGraph.cpp.
Referenced by main().
execScript()
void graph::cbComputeGraph::execScript (const std::string & script)
execute the script
Parameters
script
Definition at line 389 of file cbComputeGraph.cpp.
References graph::cbGraphSharedLuaStack::execScript(), and m_sharedLuaStack.
Referenced by main().
execScriptFile()
void graph::cbComputeGraph::execScriptFile (const std::string & filePath)
execute the script from file.
Parameters
filePath
Definition at line 385 of file cbComputeGraph.cpp.
References graph::cbGraphSharedLuaStack::execScriptFile(), and m_sharedLuaStack.
generateGraphTask()
WFGraphTask * graph::cbComputeGraph::generateGraphTask (const graph_callback & func = nullptr)
Create the graph task.
Parameters
func
Returns
WFGraphTask*
Definition at line 348 of file cbComputeGraph.cpp.
References isDAG(), isSingleOutput(), graph::Leaf, m_idx, m_nodes, m_waitGroup, graph::Operator, and graph::Output.
Referenced by main().
getId()
int32_t graph::cbComputeGraph::getId ()
Get the Id object.
Returns
int32_t
Definition at line 346 of file cbComputeGraph.cpp.
References m_idx.
isDAG()
bool graph::cbComputeGraph::isDAG ()
To judge the Graph is DAG or not.
Returns
true
false
Definition at line 259 of file cbComputeGraph.cpp.
References isSingleOutput(), m_nodes, and graph::cbNode::nextNode.
Referenced by cbComputeGraph(), and generateGraphTask().
isSingleOutput()
bool graph::cbComputeGraph::isSingleOutput ()
To judge the graph has single output or not.
Returns
true
false
Definition at line 273 of file cbComputeGraph.cpp.
References m_nodes.
Referenced by cbComputeGraph(), generateGraphTask(), and isDAG().
registerNode()
void graph::cbComputeGraph::registerNode (cbNode * node)
register a node. Not used by lua binding.
Parameters
node
Definition at line 341 of file cbComputeGraph.cpp.
References m_nodes.
Referenced by createCombineNode(), and createVirtualDeviceNode().
setVirtualDeviceManager()
void graph::cbComputeGraph::setVirtualDeviceManager (trivial::cbVirtualDeviceManager * virtualDeviceM)
Set the Virtual Device Manager object.
Parameters
virtualDeviceM
Definition at line 337 of file cbComputeGraph.cpp.
References m_virtualDevice.
Referenced by main().
Member Data Documentation
cbVirtualDeviceNode
friend graph::cbComputeGraph::cbVirtualDeviceNode
Definition at line 194 of file cbComputeGraph.hpp.
Referenced by createVirtualDeviceNode().
m_idx
int32_t graph::cbComputeGraph::m_idx = 0 private
Definition at line 340 of file cbComputeGraph.hpp.
Referenced by generateGraphTask(), and getId().
m_nodes
std::vector<cbNode*> graph::cbComputeGraph::m_nodes private
Definition at line 341 of file cbComputeGraph.hpp.
Referenced by generateGraphTask(), isDAG(), isSingleOutput(), registerNode(), and ~cbComputeGraph().
m_sharedLuaStack
cbGraphSharedLuaStack* graph::cbComputeGraph::m_sharedLuaStack = nullptr private
Definition at line 343 of file cbComputeGraph.hpp.
Referenced by cbComputeGraph(), execScript(), execScriptFile(), and ~cbComputeGraph().
m_sharedMem
cbGraphSharedMem* graph::cbComputeGraph::m_sharedMem = nullptr private
Definition at line 342 of file cbComputeGraph.hpp.
Referenced by createCell(), and ~cbComputeGraph().
m_virtualDevice
trivial::cbVirtualDeviceManager* graph::cbComputeGraph::m_virtualDevice = nullptr private
Definition at line 347 of file cbComputeGraph.hpp.
Referenced by createVirtualDeviceNode(), and setVirtualDeviceManager().
m_waitGroup
WFFacilities::WaitGroup graph::cbComputeGraph::m_waitGroup private
Definition at line 345 of file cbComputeGraph.hpp.
Referenced by generateGraphTask().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp