Covalent Bond: cb::utils::cbWebserver Class Reference
cb::utils::cbWebserver Class Reference
#include <cbWebserver.hpp>
Public Member Functions
cbWebserver ()=default
cbWebserver (const int32_t &port, const std::string &root)
Construct a new cb Webserver object.
~cbWebserver ()
void execMain ()
void stopMain ()
WFHttpServer * getServer ()
Get the Server object.
Static Private Member Functions
static void signal_kill (int signo)
Private Attributes
int32_t m_port
std::string m_root
WFHttpServer * m_server
Detailed Description
Definition at line 50 of file cbWebserver.hpp.
Constructor & Destructor Documentation
cbWebserver() [1/2]
cb::utils::cbWebserver::cbWebserver () default
cbWebserver() [2/2]
cb::utils::cbWebserver::cbWebserver (const int32_t & port, const std::string & root)
Construct a new cb Webserver object.
Parameters
port
root
Definition at line 18 of file cbWebserver.cpp.
References m_root, and m_server.
~cbWebserver()
cb::utils::cbWebserver::~cbWebserver ()
Definition at line 16 of file cbWebserver.cpp.
References m_server.
Member Function Documentation
execMain()
void cb::utils::cbWebserver::execMain ()
Definition at line 82 of file cbWebserver.cpp.
References m_port, m_server, and signal_kill().
Referenced by cb::pipeline::app::execMain().
getServer()
WFHttpServer * cb::utils::cbWebserver::getServer ()
Get the Server object.
Returns
WFHttpServer*
Definition at line 101 of file cbWebserver.cpp.
References m_server.
signal_kill()
void cb::utils::cbWebserver::signal_kill (int signo) static private
Definition at line 103 of file cbWebserver.cpp.
Referenced by execMain().
stopMain()
void cb::utils::cbWebserver::stopMain ()
Definition at line 99 of file cbWebserver.cpp.
References m_server.
Referenced by cb::pipeline::app::stopMain().
Member Data Documentation
m_port
int32_t cb::utils::cbWebserver::m_port private
Definition at line 85 of file cbWebserver.hpp.
Referenced by execMain().
m_root
std::string cb::utils::cbWebserver::m_root private
Definition at line 86 of file cbWebserver.hpp.
Referenced by cbWebserver().
m_server
WFHttpServer* cb::utils::cbWebserver::m_server private
Definition at line 87 of file cbWebserver.hpp.
Referenced by cbWebserver(), execMain(), getServer(), stopMain(), and ~cbWebserver().
The documentation for this class was generated from the following files:
/home/wang/covalentBond/src/core/utils/cbWebserver.hpp
/home/wang/covalentBond/src/core/utils/cbWebserver.cpp