Covalent Bond: /home/wang/covalentBond/src/core/server/task/luaEngine.hpp File Reference
luaEngine.hpp File Reference
A lua engine for execute all c++ embedding in struct. A warper of lua JIT engine.
#include "../../pch.hpp"
#include <lua.h>
#include <luajit.h>
#include <lauxlib.h>
#include <lualib.h>
#include <any>
#include "cbTable.hpp"
#include "cbOperator.hpp"
Classes
class luaJitThread
Functions
void bindAllFuncByDefault (sol::state *handle)
_WIN32
Detailed Description
A lua engine for execute all c++ embedding in struct. A warper of lua JIT engine.
Author
chenghua Wang (cheng.nosp@m.hua..nosp@m.wang..nosp@m.edu@.nosp@m.gmail.nosp@m..com)
Version
0.1
Date
2022-10-27
Copyright
Copyright (c) 2022
Definition in file luaEngine.hpp.
Function Documentation
bindAllFuncByDefault()
void bindAllFuncByDefault (sol::state * handle)
_WIN32
defined(unix) && defined(clang) make compiled in C ABI, and all libs is installed to system path.
Definition at line 13 of file luaEngine.cpp.
References cbMySQLCell::asDatetime(), cbMySQLCell::asDouble(), cbMySQLCell::asFloat(), cbMySQLCell::asInt(), cbMySQLCell::asString(), cbMySQLCell::asTime(), cbMySQLCell::asULL(), cbMySQLCell::isDatetime(), cbMySQLCell::isDouble(), cbMySQLCell::isFloat(), cbMySQLCell::isInt(), cbMySQLCell::isString(), cbMySQLCell::isTime(), cbMySQLCell::isULL(), MAKE_SHARED, makeShapeCol(), makeShapeFull(), makeShapeRow(), cbMySQLCell::setDatetime(), cbMySQLCell::setFloat(), cbMySQLCell::setInt(), cbMySQLCell::setString(), cbMySQLCell::setTime(), and cbMySQLCell::setULL().
Referenced by luaJitThread::luaJitThread().