Covalent Bond: /home/wang/covalentBond/src/core/server/main.cpp File Reference
main.cpp File Reference
#include "argparse.hpp"
#include "pipeline.hpp"
Macros
#define HELP_STR "\Licensed under the Apache License, Version 2.0 (the \" License \")\n\You may obtain a copy of the License at\n\\n\http://www.apache.org/licenses/LICENSE-2.0\n\\n\Unless required by applicable law or agreed to in writing, software\n\distributed under the License is distributed on an \" AS IS \" BASIS,\n\WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\See the License for the specific language governing permissions and\n\limitations under the License.\n"
#define WELCOME_STR "Welcome to CovalentBond."
Functions
static WFFacilities::WaitGroup wait_group (1)
static WFFacilities::WaitGroup wait_group_end (1)
void sig_handler (int signo)
int main (int argc, char *argv[])
Macro Definition Documentation
HELP_STR
#define HELP_STR "\Licensed under the Apache License, Version 2.0 (the \" License \")\n\You may obtain a copy of the License at\n\\n\http://www.apache.org/licenses/LICENSE-2.0\n\\n\Unless required by applicable law or agreed to in writing, software\n\distributed under the License is distributed on an \" AS IS \" BASIS,\n\WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\See the License for the specific language governing permissions and\n\limitations under the License.\n"
Definition at line 4 of file main.cpp.
WELCOME_STR
#define WELCOME_STR "Welcome to CovalentBond."
Definition at line 17 of file main.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file main.cpp.
References argp::parser::add_arg(), argp::parser::get_item(), cb::pipeline::appCfg::graphExecSec, argp::parser::has_item(), HELP_STR, argp::parser::parse(), cb::pipeline::appCfg::redisDBNum, cb::pipeline::appCfg::redisHost, cb::pipeline::appCfg::redisPassword, cb::pipeline::appCfg::redisPort, cb::pipeline::appCfg::redisSSL, cb::pipeline::appCfg::rHttpPort, argp::parser::show_all_defined(), sig_handler(), argp::t_int, argp::t_string, wait_group(), wait_group_end(), cb::pipeline::appCfg::webPort, cb::pipeline::appCfg::webRoot, and WELCOME_STR.
sig_handler()
void sig_handler (int signo)
Definition at line 22 of file main.cpp.
References wait_group().
Referenced by main().
wait_group()
static WFFacilities::WaitGroup wait_group (1) static
Referenced by main(), and sig_handler().
wait_group_end()
static WFFacilities::WaitGroup wait_group_end (1) static
Referenced by main().