Covalent Bond: cb::trans Namespace Reference
cb::trans Namespace Reference
Classes
struct leafMapStruct
struct opMapStruct
Functions
void outbase (HttpResp *resp)
void createLeafNode (HttpResp *resp, cb::trans::leafMapStruct &leafMapStruct, trivial::cbMySqlDevice *leafNode)
void createOpNode (HttpResp *resp, cb::trans::opMapStruct &opMapStruct)
void createFinNode (int posy, int opCodeNow, HttpResp *resp)
void Node_leaf_connect (int nodeleftnum, int noderightnum, int nowinputsnum, HttpResp *resp)
void Node_op_connect (int nodeleftnum, int nowinputsnum, HttpResp *resp)
void outbaseo (HttpResp *resp)
Function Documentation
createFinNode()
void cb::trans::createFinNode (int posy, int opCodeNow, HttpResp * resp)
Definition at line 104 of file api.cpp.
Referenced by cb::pipeline::app::initRHttp().
createLeafNode()
void cb::trans::createLeafNode (HttpResp * resp, cb::trans::leafMapStruct & leafMapStruct, trivial::cbMySqlDevice * leafNode)
Definition at line 38 of file api.cpp.
References trivial::cbVirtualDevice::dataBaseName, trivial::cbVirtualDevice::host, cb::trans::leafMapStruct::nodeCode, trivial::cbVirtualDevice::passWord, trivial::cbVirtualDevice::port, cb::trans::leafMapStruct::posy, and trivial::cbVirtualDevice::usrName.
Referenced by cb::pipeline::app::initRHttp().
createOpNode()
void cb::trans::createOpNode (HttpResp * resp, cb::trans::opMapStruct & opMapStruct)
Definition at line 76 of file api.cpp.
References cb::trans::opMapStruct::inputNum, cb::trans::opMapStruct::nodeCode, and cb::trans::opMapStruct::posy.
Referenced by cb::pipeline::app::initRHttp().
Node_leaf_connect()
void cb::trans::Node_leaf_connect (int nodeleftnum, int noderightnum, int nowinputsnum, HttpResp * resp)
Definition at line 126 of file api.cpp.
Referenced by cb::pipeline::app::initRHttp().
Node_op_connect()
void cb::trans::Node_op_connect (int nodeleftnum, int nowinputsnum, HttpResp * resp)
Definition at line 132 of file api.cpp.
Referenced by cb::pipeline::app::initRHttp().
outbase()
void cb::trans::outbase (HttpResp * resp)
Definition at line 20 of file api.cpp.
Referenced by cb::pipeline::app::initRHttp().
outbaseo()
void cb::trans::outbaseo (HttpResp * resp)
Definition at line 139 of file api.cpp.
Referenced by cb::pipeline::app::initRHttp().