Covalent Bond: cb::apiCPP Namespace Reference
cb::apiCPP Namespace Reference
Functions
cb::graph::cbComputeGraph * addGraph (int32_t idx, const std::string &cmd, trivial::cbVirtualDeviceManager *vdm)
Function Documentation
addGraph()
cb::graph::cbComputeGraph * cb::apiCPP::addGraph (int32_t idx, const std::string & cmd, trivial::cbVirtualDeviceManager * vdm)
Definition at line 6 of file api.cpp.
References cb::graph::cbComputeGraph::execScript(), and cb::graph::cbComputeGraph::setVirtualDeviceManager().
Referenced by cb::pipeline::app::initRHttp().