Covalent Bond: graph::cbVirtualDeviceNode Struct Reference
graph::cbVirtualDeviceNode Struct Reference final
This node include virtual device infomation and perform the final operation of how to get the data from remote sql database.
#include <cbComputeGraph.hpp>
Public Member Functions
~cbVirtualDeviceNode () override final
cbVirtualDeviceNode ()
void * generateTask () override final
generate a SQL wf task for now.
void addQuery (const std::string &q)
Add a String type sql sentence to this node. Waiting to be execute.
Public Member Functions inherited from graph::cbNode
virtual ~cbNode ()
cbNode (const nodeType &nt)
void PointTo (cbNode *ptr)
Public Attributes
friend cbComputeGraph
Public Attributes inherited from graph::cbNode
cbOpIO io
nodeType nodeT
void * task = nullptr
cbNode * nextNode = nullptr
cbComputeGraph * graph = nullptr
Private Member Functions
void setMySQLDevice (trivial::cbMySqlDevice *device=nullptr)
Private Attributes
trivial::cbMySqlDevice * m_device
std::vector< std::string > m_queries
Additional Inherited Members
Static Public Member Functions inherited from graph::cbNode
static WFMySQLTask * asSQLTask (void *metaTask)
static WFGoTask * asGoTask (void *metaTask)
Detailed Description
This node include virtual device infomation and perform the final operation of how to get the data from remote sql database.
Note
This node just support SQL for now. But it's quite easy to extened to other relationship database.
Definition at line 134 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
~cbVirtualDeviceNode()
graph::cbVirtualDeviceNode::~cbVirtualDeviceNode () final override
Definition at line 49 of file cbComputeGraph.cpp.
cbVirtualDeviceNode()
graph::cbVirtualDeviceNode::cbVirtualDeviceNode ()
Definition at line 93 of file cbComputeGraph.cpp.
References graph::Leaf.
Member Function Documentation
addQuery()
void graph::cbVirtualDeviceNode::addQuery (const std::string & q)
Add a String type sql sentence to this node. Waiting to be execute.
Parameters
q string
Definition at line 89 of file cbComputeGraph.cpp.
References m_queries.
Referenced by graph::cbComputeGraph::cbComputeGraph().
generateTask()
void * graph::cbVirtualDeviceNode::generateTask () final override virtual
generate a SQL wf task for now.
Returns
void* WFMySQLTask* actually.
Implements graph::cbNode.
Definition at line 53 of file cbComputeGraph.cpp.
References cbOpIO::I, graph::cbNode::io, m_device, m_queries, mapShared2Virtual(), graph::cbNode::nextNode, cbOpIO::O, trivial::cbMySqlDevice::query(), and graph::cbNode::task.
setMySQLDevice()
void graph::cbVirtualDeviceNode::setMySQLDevice (trivial::cbMySqlDevice * device = nullptr) private
Definition at line 91 of file cbComputeGraph.cpp.
References m_device.
Referenced by graph::cbComputeGraph::createVirtualDeviceNode().
Member Data Documentation
cbComputeGraph
friend graph::cbVirtualDeviceNode::cbComputeGraph
Definition at line 135 of file cbComputeGraph.hpp.
m_device
trivial::cbMySqlDevice* graph::cbVirtualDeviceNode::m_device private
Definition at line 156 of file cbComputeGraph.hpp.
Referenced by generateTask(), and setMySQLDevice().
m_queries
std::vector<std::string> graph::cbVirtualDeviceNode::m_queries private
Definition at line 157 of file cbComputeGraph.hpp.
Referenced by addQuery(), and generateTask().
The documentation for this struct was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp