Covalent Bond: cb::graph::cbRedisCachingNode Struct Reference
cb::graph::cbRedisCachingNode Struct Reference final
#include <cbComputeGraph.hpp>
Public Member Functions
~cbRedisCachingNode () override final
cbRedisCachingNode ()=delete
cbRedisCachingNode (int32_t idx)
cbRedisCachingNode (const cbRedisCachingNode &v)=delete
cbRedisCachingNode operator= (const cbRedisCachingNode &v)=delete
void * generateTask () override final
WFRedisTask * _generateSetTask (const std::vector< std::string > &params, const redis_callback &callback_func=nullptr, void *usrData=nullptr, int32_t retryTimes=3)
Public Member Functions inherited from cb::graph::cbNode
virtual ~cbNode ()
Destroy the cb Node object Virtual function.
cbNode (const nodeType &nt)
void PointTo (cbNode *ptr)
Public Attributes
friend cbComputeGraph
Public Attributes inherited from cb::graph::cbNode
cbOpIO io
bool isFinalOutput = false
bool visited = false
nodeType nodeT
void * task = nullptr
cbNode * nextNode = nullptr
cbComputeGraph * graph = nullptr
Private Member Functions
void setRedisDevice (trivial::cbRedisDevice *device=nullptr)
Private Attributes
int32_t m_idx
trivial::cbRedisDevice * m_device = nullptr
Additional Inherited Members
Static Public Member Functions inherited from cb::graph::cbNode
static WFMySQLTask * asSQLTask (void *metaTask)
static WFGoTask * asGoTask (void *metaTask)
Detailed Description
Definition at line 286 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
~cbRedisCachingNode()
cb::graph::cbRedisCachingNode::~cbRedisCachingNode () final override
Definition at line 126 of file cbComputeGraph.cpp.
cbRedisCachingNode() [1/3]
cb::graph::cbRedisCachingNode::cbRedisCachingNode () delete
cbRedisCachingNode() [2/3]
cb::graph::cbRedisCachingNode::cbRedisCachingNode (int32_t idx)
Definition at line 124 of file cbComputeGraph.cpp.
References cb::graph::Output.
cbRedisCachingNode() [3/3]
cb::graph::cbRedisCachingNode::cbRedisCachingNode (const cbRedisCachingNode & v) delete
Member Function Documentation
_generateSetTask()
WFRedisTask * cb::graph::cbRedisCachingNode::_generateSetTask (const std::vector< std::string > & params, const redis_callback & callback_func = nullptr, void * usrData = nullptr, int32_t retryTimes = 3)
Definition at line 133 of file cbComputeGraph.cpp.
References m_device, and trivial::cbRedisDevice::set().
Referenced by cb::graph::cbComputeGraph::generateGraphTask().
generateTask()
void * cb::graph::cbRedisCachingNode::generateTask () final override virtual
Implements cb::graph::cbNode.
Definition at line 128 of file cbComputeGraph.cpp.
operator=()
cbRedisCachingNode cb::graph::cbRedisCachingNode::operator= (const cbRedisCachingNode & v) delete
setRedisDevice()
void cb::graph::cbRedisCachingNode::setRedisDevice (trivial::cbRedisDevice * device = nullptr) private
Definition at line 139 of file cbComputeGraph.cpp.
References m_device.
Referenced by cb::graph::cbComputeGraph::createRedisCachingNode().
Member Data Documentation
cbComputeGraph
friend cb::graph::cbRedisCachingNode::cbComputeGraph
Definition at line 287 of file cbComputeGraph.hpp.
m_device
trivial::cbRedisDevice* cb::graph::cbRedisCachingNode::m_device = nullptr private
Definition at line 305 of file cbComputeGraph.hpp.
Referenced by _generateSetTask(), and setRedisDevice().
m_idx
int32_t cb::graph::cbRedisCachingNode::m_idx private
Definition at line 304 of file cbComputeGraph.hpp.
The documentation for this struct was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp