Covalent Bond: cb::graph::cbGraphSharedMem Struct Reference
cb::graph::cbGraphSharedMem Struct Reference
The shared memory of compute graph. Include 2 basic components.
#include <cbComputeGraph.hpp>
Public Member Functions
cbGraphSharedMem ()=default
Construct a new cb Graph Shared Mem object.
cbGraphSharedMem (cbGraphSharedMem &rhs)=delete
Construct a new cb Graph Shared Mem object.
cbGraphSharedMem (const cbGraphSharedMem &rhs)=delete
Construct a new cb Graph Shared Mem object.
cbGraphSharedMem operator= (cbGraphSharedMem &rhs)=delete
operator of = is deleted
cbGraphSharedMem operator= (const cbGraphSharedMem &rhs)=delete
operator of const = is deleted
~cbGraphSharedMem ()
Destroy the cb Graph Shared Mem object.
void push (cbVirtualSharedTable *v)
Push a virtual shared table to mem of graph.
void push (cbMySQLCell *v)
Push a Sql Cell to mem of graph.
void push (cbMySQLField *v)
Push a Sql field to mem of graph.
void setOutStruct (const cbShape< 2 > &shape, cbMySQLField **info)
Set the Out Struct object.
size_t getMemUsed ()
Get the Mem Used object.
int32_t getCellNum ()
Get the Cell Num object.
cbOutputTableStruct * getOutStruct ()
Get the Out Struct object.
void clear ()
Private Attributes
cbOutputTableStruct * m_outStruct = nullptr
std::vector< cbVirtualSharedTable * > m_dataFromDevice
std::vector< cbMySQLCell * > m_dataPool
std::vector< cbMySQLField * > m_fields
Detailed Description
The shared memory of compute graph. Include 2 basic components.
The Virtual Shared Table
The Shared memory pool. Worked as a vector.
Definition at line 63 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
cbGraphSharedMem() [1/3]
cb::graph::cbGraphSharedMem::cbGraphSharedMem () default
Construct a new cb Graph Shared Mem object.
cbGraphSharedMem() [2/3]
cb::graph::cbGraphSharedMem::cbGraphSharedMem (cbGraphSharedMem & rhs) delete
Construct a new cb Graph Shared Mem object.
Parameters
rhs deleted
cbGraphSharedMem() [3/3]
cb::graph::cbGraphSharedMem::cbGraphSharedMem (const cbGraphSharedMem & rhs) delete
Construct a new cb Graph Shared Mem object.
Parameters
rhs
~cbGraphSharedMem()
cb::graph::cbGraphSharedMem::~cbGraphSharedMem ()
Destroy the cb Graph Shared Mem object.
Definition at line 7 of file cbComputeGraph.cpp.
References m_dataFromDevice, and m_dataPool.
Member Function Documentation
clear()
void cb::graph::cbGraphSharedMem::clear ()
Definition at line 46 of file cbComputeGraph.cpp.
References cbOutputTableStruct::clear(), m_dataFromDevice, m_dataPool, m_fields, and m_outStruct.
Referenced by cb::graph::cbComputeGraph::generateGraphTask().
getCellNum()
int32_t cb::graph::cbGraphSharedMem::getCellNum ()
Get the Cell Num object.
Returns
int32_t
Definition at line 35 of file cbComputeGraph.cpp.
References m_dataFromDevice, and m_dataPool.
getMemUsed()
size_t cb::graph::cbGraphSharedMem::getMemUsed ()
Get the Mem Used object.
Returns
size_t
Definition at line 26 of file cbComputeGraph.cpp.
References m_dataFromDevice, and m_dataPool.
getOutStruct()
cbOutputTableStruct * cb::graph::cbGraphSharedMem::getOutStruct ()
Get the Out Struct object.
Returns
cbOutputTableStruct*
Definition at line 44 of file cbComputeGraph.cpp.
References m_outStruct.
Referenced by cb::graph::cbComputeGraph::generateGraphTask(), and cb::graph::cbComputeGraph::getOutput().
operator=() [1/2]
cbGraphSharedMem cb::graph::cbGraphSharedMem::operator= (cbGraphSharedMem & rhs) delete
operator of = is deleted
Parameters
rhs
Returns
cbGraphSharedMem
operator=() [2/2]
cbGraphSharedMem cb::graph::cbGraphSharedMem::operator= (const cbGraphSharedMem & rhs) delete
operator of const = is deleted
Parameters
rhs
Returns
cbGraphSharedMem
push() [1/3]
void cb::graph::cbGraphSharedMem::push (cbMySQLCell * v)
Push a Sql Cell to mem of graph.
Parameters
v
Definition at line 14 of file cbComputeGraph.cpp.
References m_dataPool.
push() [2/3]
void cb::graph::cbGraphSharedMem::push (cbMySQLField * v)
Push a Sql field to mem of graph.
Parameters
v
Definition at line 16 of file cbComputeGraph.cpp.
References m_fields.
push() [3/3]
void cb::graph::cbGraphSharedMem::push (cbVirtualSharedTable * v)
Push a virtual shared table to mem of graph.
Parameters
v
Definition at line 12 of file cbComputeGraph.cpp.
References m_dataFromDevice.
Referenced by cb::graph::cbComputeGraph::createCell(), and cb::graph::cbVirtualDeviceNode::generateTask().
setOutStruct()
void cb::graph::cbGraphSharedMem::setOutStruct (const cbShape< 2 > & shape, cbMySQLField ** info)
Set the Out Struct object.
Parameters
shape the shape of output virtual table.
info the ptr-ptr of sql field
Definition at line 18 of file cbComputeGraph.cpp.
References m_outStruct, and cbOutputTableStruct::update().
Referenced by cb::graph::cbVirtualDeviceNode::generateTask().
Member Data Documentation
m_dataFromDevice
std::vector<cbVirtualSharedTable*> cb::graph::cbGraphSharedMem::m_dataFromDevice private
Definition at line 161 of file cbComputeGraph.hpp.
Referenced by clear(), getCellNum(), getMemUsed(), push(), and ~cbGraphSharedMem().
m_dataPool
std::vector<cbMySQLCell*> cb::graph::cbGraphSharedMem::m_dataPool private
Definition at line 162 of file cbComputeGraph.hpp.
Referenced by clear(), getCellNum(), getMemUsed(), push(), and ~cbGraphSharedMem().
m_fields
std::vector<cbMySQLField*> cb::graph::cbGraphSharedMem::m_fields private
Definition at line 163 of file cbComputeGraph.hpp.
Referenced by clear(), and push().
m_outStruct
cbOutputTableStruct* cb::graph::cbGraphSharedMem::m_outStruct = nullptr private
Definition at line 160 of file cbComputeGraph.hpp.
Referenced by clear(), getOutStruct(), and setOutStruct().
The documentation for this struct was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp