Covalent Bond: cb::graph::cbVirtualDeviceNode Struct Reference
cb::graph::cbVirtualDeviceNode Struct Reference final
This node include virtual device infomation and perform the final operation of how to get the data from remote sql database.
#include <cbComputeGraph.hpp>
Public Member Functions
~cbVirtualDeviceNode () override final
cbVirtualDeviceNode ()
void * generateTask () override final
generate a SQL wf task for now.
void addQuery (const std::string &q)
Add a String type sql sentence to this node. Waiting to be execute.
trivial::cbMySqlDevice * getDevice ()
Get the Device object.
Public Member Functions inherited from cb::graph::cbNode
virtual ~cbNode ()
Destroy the cb Node object Virtual function.
cbNode (const nodeType &nt)
void PointTo (cbNode *ptr)
Public Attributes
friend cbComputeGraph
Public Attributes inherited from cb::graph::cbNode
cbOpIO io
bool isFinalOutput = false
bool visited = false
nodeType nodeT
void * task = nullptr
cbNode * nextNode = nullptr
cbComputeGraph * graph = nullptr
Private Member Functions
void setMySQLDevice (trivial::cbMySqlDevice *device=nullptr)
Private Attributes
trivial::cbMySqlDevice * m_device
std::vector< std::string > m_queries
Additional Inherited Members
Static Public Member Functions inherited from cb::graph::cbNode
static WFMySQLTask * asSQLTask (void *metaTask)
static WFGoTask * asGoTask (void *metaTask)
Detailed Description
This node include virtual device infomation and perform the final operation of how to get the data from remote sql database.
Note
This node just support SQL for now. But it's quite easy to extened to other relationship database.
Definition at line 253 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
~cbVirtualDeviceNode()
cb::graph::cbVirtualDeviceNode::~cbVirtualDeviceNode () final override
Definition at line 72 of file cbComputeGraph.cpp.
cbVirtualDeviceNode()
cb::graph::cbVirtualDeviceNode::cbVirtualDeviceNode ()
Definition at line 122 of file cbComputeGraph.cpp.
References cb::graph::Leaf.
Member Function Documentation
addQuery()
void cb::graph::cbVirtualDeviceNode::addQuery (const std::string & q)
Add a String type sql sentence to this node. Waiting to be execute.
Parameters
q string
Definition at line 116 of file cbComputeGraph.cpp.
References m_queries.
Referenced by cb::graph::cbComputeGraph::cbComputeGraph().
generateTask()
void * cb::graph::cbVirtualDeviceNode::generateTask () final override virtual
generate a SQL wf task for now.
Returns
void* WFMySQLTask* actually.
Implements cb::graph::cbNode.
Definition at line 76 of file cbComputeGraph.cpp.
References cbVirtualTable::getInfo(), cbVirtualTable::getShape(), cb::graph::cbNode::graph, cbOpIO::I, cb::graph::cbNode::io, cb::graph::cbComputeGraph::io, cb::graph::cbNode::isFinalOutput, m_device, m_queries, cb::graph::cbComputeGraph::m_sharedMem, mapShared2Virtual(), cb::graph::cbNode::nextNode, cbOpIO::O, cb::graph::cbGraphSharedMem::push(), trivial::cbMySqlDevice::query(), cb::graph::cbGraphSharedMem::setOutStruct(), and cb::graph::cbNode::task.
getDevice()
trivial::cbMySqlDevice * cb::graph::cbVirtualDeviceNode::getDevice ()
Get the Device object.
Returns
trivial::cbMySqlDevice*
Definition at line 118 of file cbComputeGraph.cpp.
References m_device.
setMySQLDevice()
void cb::graph::cbVirtualDeviceNode::setMySQLDevice (trivial::cbMySqlDevice * device = nullptr) private
Definition at line 120 of file cbComputeGraph.cpp.
References m_device.
Referenced by cb::graph::cbComputeGraph::createVirtualDeviceNode().
Member Data Documentation
cbComputeGraph
friend cb::graph::cbVirtualDeviceNode::cbComputeGraph
Definition at line 254 of file cbComputeGraph.hpp.
m_device
trivial::cbMySqlDevice* cb::graph::cbVirtualDeviceNode::m_device private
Definition at line 282 of file cbComputeGraph.hpp.
Referenced by generateTask(), getDevice(), and setMySQLDevice().
m_queries
std::vector<std::string> cb::graph::cbVirtualDeviceNode::m_queries private
Definition at line 283 of file cbComputeGraph.hpp.
Referenced by addQuery(), and generateTask().
The documentation for this struct was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp