Covalent Bond: graph::cbGraphSharedLuaStack Struct Reference
graph::cbGraphSharedLuaStack Struct Reference
#include <cbComputeGraph.hpp>
Public Member Functions
cbGraphSharedLuaStack ()=default
cbGraphSharedLuaStack (const cbGraphSharedLuaStack &)=delete
cbGraphSharedLuaStack operator= (const cbGraphSharedLuaStack &)=delete
void execScriptFile (const std::string &filePath)
execute the script file from disk directly.
void execScript (const std::string &script)
execute the hard coded script.
luaJitThread & get ()
get the lua state.
Private Attributes
luaJitThread m_lua
Detailed Description
Definition at line 72 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
cbGraphSharedLuaStack() [1/2]
graph::cbGraphSharedLuaStack::cbGraphSharedLuaStack () default
cbGraphSharedLuaStack() [2/2]
graph::cbGraphSharedLuaStack::cbGraphSharedLuaStack (const cbGraphSharedLuaStack &) delete
Member Function Documentation
execScript()
void graph::cbGraphSharedLuaStack::execScript (const std::string & script)
execute the hard coded script.
Parameters
script
Definition at line 37 of file cbComputeGraph.cpp.
References m_lua.
Referenced by graph::cbComputeGraph::execScript().
execScriptFile()
void graph::cbGraphSharedLuaStack::execScriptFile (const std::string & filePath)
execute the script file from disk directly.
Parameters
filePath string.
Definition at line 33 of file cbComputeGraph.cpp.
References m_lua.
Referenced by graph::cbComputeGraph::execScriptFile().
get()
luaJitThread & graph::cbGraphSharedLuaStack::get ()
get the lua state.
Returns
luaJitThread&
Definition at line 39 of file cbComputeGraph.cpp.
References m_lua.
Referenced by graph::cbComputeGraph::cbComputeGraph().
operator=()
cbGraphSharedLuaStack graph::cbGraphSharedLuaStack::operator= (const cbGraphSharedLuaStack &) delete
Member Data Documentation
m_lua
luaJitThread graph::cbGraphSharedLuaStack::m_lua private
Definition at line 99 of file cbComputeGraph.hpp.
Referenced by execScript(), execScriptFile(), and get().
The documentation for this struct was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp