Covalent Bond: cbOutputTableStruct Struct Reference
cbOutputTableStruct Struct Reference
#include <cbTable.hpp>
Public Member Functions
cbOutputTableStruct ()=delete
cbOutputTableStruct (const cbShape< 2 > &shape, cbMySQLField **info)
void clear ()
void update (const cbShape< 2 > &shape, cbMySQLField **info)
std::string genKey4Redis (int32_t row, int32_t col)
Public Attributes
cbShape< 2 > m_shape
std::vector< cbMySQLField > m_info
Detailed Description
Definition at line 776 of file cbTable.hpp.
Constructor & Destructor Documentation
cbOutputTableStruct() [1/2]
cbOutputTableStruct::cbOutputTableStruct () delete
cbOutputTableStruct() [2/2]
cbOutputTableStruct::cbOutputTableStruct (const cbShape< 2 > & shape, cbMySQLField ** info)
Definition at line 204 of file cbTable.cpp.
References m_info, and m_shape.
Member Function Documentation
clear()
void cbOutputTableStruct::clear ()
Definition at line 210 of file cbTable.cpp.
Referenced by cb::graph::cbGraphSharedMem::clear(), and update().
genKey4Redis()
std::string cbOutputTableStruct::genKey4Redis (int32_t row, int32_t col)
Definition at line 224 of file cbTable.cpp.
References m_info.
update()
void cbOutputTableStruct::update (const cbShape< 2 > & shape, cbMySQLField ** info)
Definition at line 217 of file cbTable.cpp.
References clear(), m_info, and m_shape.
Referenced by cb::graph::cbGraphSharedMem::setOutStruct().
Member Data Documentation
m_info
std::vector<cbMySQLField> cbOutputTableStruct::m_info
Definition at line 787 of file cbTable.hpp.
Referenced by cbOutputTableStruct(), genKey4Redis(), and update().
m_shape
cbShape<2> cbOutputTableStruct::m_shape
Definition at line 786 of file cbTable.hpp.
Referenced by cbOutputTableStruct(), cb::graph::cbComputeGraph::generateGraphTask(), cb::pipeline::app::initRHttp(), and update().
The documentation for this struct was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbTable.hpp
/home/wang/covalentBond/src/core/server/task/cbTable.cpp