Covalent Bond: cb::graph::cbGraphSharedLuaStack Struct Reference
cb::graph::cbGraphSharedLuaStack Struct Reference
#include <cbComputeGraph.hpp>
Public Member Functions
cbGraphSharedLuaStack ()=default
Construct a new cb Graph Shared Lua Stack object.
cbGraphSharedLuaStack (const cbGraphSharedLuaStack &)=delete
Construct a new cb Graph Shared Lua Stack object using const cbGraphSharedLuaStack& is deleted.
cbGraphSharedLuaStack operator= (const cbGraphSharedLuaStack &)=delete
operator of const = is deleted
void execScriptFile (const std::string &filePath)
execute the script file from disk directly.
void execScript (const std::string &script)
execute the hard coded script.
luaJitThread & get ()
get the lua state.
Private Attributes
luaJitThread m_lua
Detailed Description
Definition at line 170 of file cbComputeGraph.hpp.
Constructor & Destructor Documentation
cbGraphSharedLuaStack() [1/2]
cb::graph::cbGraphSharedLuaStack::cbGraphSharedLuaStack () default
Construct a new cb Graph Shared Lua Stack object.
cbGraphSharedLuaStack() [2/2]
cb::graph::cbGraphSharedLuaStack::cbGraphSharedLuaStack (const cbGraphSharedLuaStack &) delete
Construct a new cb Graph Shared Lua Stack object using const cbGraphSharedLuaStack& is deleted.
Member Function Documentation
execScript()
void cb::graph::cbGraphSharedLuaStack::execScript (const std::string & script)
execute the hard coded script.
Parameters
script
Definition at line 60 of file cbComputeGraph.cpp.
References m_lua.
Referenced by cb::graph::cbComputeGraph::execScript().
execScriptFile()
void cb::graph::cbGraphSharedLuaStack::execScriptFile (const std::string & filePath)
execute the script file from disk directly.
Parameters
filePath string.
Definition at line 56 of file cbComputeGraph.cpp.
References m_lua.
Referenced by cb::graph::cbComputeGraph::execScriptFile().
get()
luaJitThread & cb::graph::cbGraphSharedLuaStack::get ()
get the lua state.
Returns
luaJitThread&
Definition at line 62 of file cbComputeGraph.cpp.
References m_lua.
Referenced by cb::graph::cbComputeGraph::cbComputeGraph(), and cb::graph::cbComputeGraph::createCombineNode().
operator=()
cbGraphSharedLuaStack cb::graph::cbGraphSharedLuaStack::operator= (const cbGraphSharedLuaStack &) delete
operator of const = is deleted
Returns
cbGraphSharedLuaStack
Member Data Documentation
m_lua
luaJitThread cb::graph::cbGraphSharedLuaStack::m_lua private
Definition at line 212 of file cbComputeGraph.hpp.
Referenced by execScript(), execScriptFile(), and get().
The documentation for this struct was generated from the following files:
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.hpp
/home/wang/covalentBond/src/core/server/task/cbComputeGraph.cpp